name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check learner-built demo is running properly
      id: check-learner-built-demo-is-running-properly
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Check learner-built demo is running properly
        setup-command: sudo -H pip3 install -r requirements.txt
        command: pytest
        timeout: 5
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHECK-LEARNER-BUILT-DEMO-IS-RUNNING-PROPERLY_RESULTS: "${{steps.check-learner-built-demo-is-running-properly.outputs.result}}"
      with:
        runners: check-learner-built-demo-is-running-properly